# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DutchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ActionSheetPicker-3.0'

  # Pods for DutchApp

end
